language: cpp
compiler:
  - gcc
before_install:
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install build-essential cmake libboost-all-dev liblzma-dev
script: mkdir build && cd build && cmake .. && make
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - daniel@constexpr.org
    on_success: change
    on_failure: always
